[package]

name = "postgres_extension_macros"
version = "0.0.1"
authors = ["Daniel Fagnan <dnfagnan@gmail.com>",
	   "Jeff Davis <jeff@davisjeff.com>"]

[lib]
name = "postgres_extension_macros"
crate-type = ["rlib"]
